SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0//
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0//

DROP TABLE IF EXISTS `email`//
DROP TABLE IF EXISTS `user`//

CREATE TABLE `email` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`email` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
//


CREATE TABLE `user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
  `username` VARCHAR(50) NOT NULL COLLATE 'utf8_bin',
  `email_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_r9kvst217faqa7vgeyy51oos0` (`email_id`),
  CONSTRAINT `FKqdcjp0ysjegpu2jb76u3f3nx` FOREIGN KEY (`email_id`) REFERENCES `email` (`id`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB
//

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS//
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS//