spring:
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/spring_persistence?autoReconnect=true&useSSL=false
    username: root
    password: Accenture1
    
    continue-on-error: false # Forcefully stop if problem found while initializing the db
        
    schema:
    - sql/schema/create-schema.sql
    data:
    - sql/data/sample-data.sql
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate  # use `create` to force creation of tables from JPA annotations
    
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect # this is needed; otherwise MyISAM engine is used instead of InnoDB
     
      
    
